name: Python unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        wget https://root.cern/download/root_v6.22.06.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
        tar -xzf root_v6.22.06.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
        alias python=python3
        source root/bin/thisroot.sh
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        python setup.py install
        which conda
    - name: Run unit tests
      run: |
        pwd; ls -lrth
        pytest tests/
